### ISSUE TITLE
docsite部署在阿里云报错

### ISSUE THREAD

**Issue by bazingabingo** [txd-team/docsite#45]
无

**Comment by bazingabingo** [comment]
根目录的问题已经解决，我是直接部署在云容器上不是在本地，docsite start后不能直接在浏览器中打开，但是访问的url是什么？

**Comment by bazingabingo** [comment]
执行docsite start之后不能首页不能访问，容器已开通8080端口。发现start时有如下信息：
[19:06:42] Using gulpfile /app/docsite/gulpfile.js
[19:06:42] Starting 'webpack-dev-server'...
[19:06:42] Finished 'webpack-dev-server' after 201 ms
[19:06:42] Starting 'default'...
[19:06:42] Finished 'default' after 23 μs
[19:06:42] [webpack-dev-server] http://127.0.0.1:8080/webpack-dev-server/index.html
(node:11990) UnhandledPromiseRejectionWarning: Error: Exited with code 3
    at ChildProcess.cp.once.code (/app/docsite/node_modules/opn/index.js:85:13)
    at Object.onceWrapper (events.js:286:20)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:606:12)
(node:11990) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11990) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Hash: 1bdb40ea3623ab4c6871
Version: webpack 2.7.0
Time: 6078ms

**Comment by purple-force** [comment]
docsite start只用于本地开发，docsite build后把文件上传到阿里云上。本质上阿里云这里需要充当的角色是静态服务器。
