### ISSUE TITLE
docsite start 出错

### ISSUE THREAD

**Issue by KSMASTERS** [txd-team/docsite#55]
<img width="1100" alt="屏幕快照 2019-09-25 下午3 31 46" src="https://user-images.githubusercontent.com/41298676/65579173-d0611080-dfa9-11e9-9da5-c02172327a32.png">

**Comment by khadgarmage** [comment]
node版本太高了吧？

**Comment by purple-force** [comment]
当前支持到node10，node版本是多少

**Comment by Sogrey** [comment]
> 当前支持到node10


我是 node v12.14.0

执行 `docsite start` 报错:

```
$ docsite start
(node:16728) UnhandledPromiseRejectionWarning: Error: Missing binding 
D:\Program Files\nodejs\node_modules\node_global\node_modules\docsite\node_modules\node-sass\vendor\win32-x64-72\binding.node
Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 12.x

Found bindings for the following environments:
  - Windows 64-bit with Node.js 12.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to download the binding for your current environment.
    at module.exports (D:\Program Files\nodejs\node_modules\node_global\node_modules\docsite\node_modules\node-sass\lib\binding.js:15:13)   
    at Object.<anonymous> (D:\Program Files\nodejs\node_modules\node_global\node_modules\docsite\node_modules\node-sass\lib\index.js:14:35) 
    at Module._compile (internal/modules/cjs/loader.js:959:30)        
    at Module._extensions..js (internal/modules/cjs/loader.js:995:10) 
    at Object.require.extensions.<computed> [as .js] (D:\Program Files\nodejs\node_modules\node_global\node_modules\docsite\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)  
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at preprocessCss (D:\Program Files\nodejs\node_modules\node_global\node_modules\docsite\lib\start.js:17:5)
(node:16728) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16728) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.  
```
