### ISSUE TITLE
docsite start failed in Mac

### ISSUE THREAD

**Issue by GindaChen** [txd-team/docsite#64]
Running on mac with nodejs `v8.16.0` prompt the following error message:
```
docsite start

(node:67521) UnhandledPromiseRejectionWarning: Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.
    at throwVersionError (/Users/mike/Project/wuhan2020.github.io/node_modules/@babel/helper-plugin-utils/lib/index.js:65:11)
    at Object.assertVersion (/Users/mike/Project/wuhan2020.github.io/node_modules/@babel/helper-plugin-utils/lib/index.js:13:11)
    at _default (/Users/mike/Project/wuhan2020.github.io/node_modules/@babel/plugin-proposal-decorators/lib/index.js:19:7)
    at /Users/mike/Project/wuhan2020.github.io/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
    at Function.memoisePluginContainer (/Users/mike/.nvm/versions/node/v8.16.0/lib/node_modules/docsite/node_modules/babel-core/lib/transformation/file/options/option-manager.js:113:13)
    at Function.normalisePlugin (/Users/mike/.nvm/versions/node/v8.16.0/lib/node_modules/docsite/node_modules/babel-core/lib/transformation/file/options/option-manager.js:146:32)
    at /Users/mike/.nvm/versions/node/v8.16.0/lib/node_modules/docsite/node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/Users/mike/.nvm/versions/node/v8.16.0/lib/node_modules/docsite/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/mike/.nvm/versions/node/v8.16.0/lib/node_modules/docsite/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/mike/.nvm/versions/node/v8.16.0/lib/node_modules/docsite/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at compile (/Users/mike/.nvm/versions/node/v8.16.0/lib/node_modules/docsite/node_modules/babel-register/lib/node.js:103:45)
    at loader (/Users/mike/.nvm/versions/node/v8.16.0/lib/node_modules/docsite/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .jsx] (/Users/mike/.nvm/versions/node/v8.16.0/lib/node_modules/docsite/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at files.forEach.file (/Users/mike/.nvm/versions/node/v8.16.0/lib/node_modules/docsite/lib/generateJSONFile.js:65:33)
    at Array.forEach (<anonymous>)
    at parse (/Users/mike/.nvm/versions/node/v8.16.0/lib/node_modules/docsite/lib/generateJSONFile.js:27:11)
    at files.forEach.file (/Users/mike/.nvm/versions/node/v8.16.0/lib/node_modules/docsite/lib/generateJSONFile.js:114:9)
    at Array.forEach (<anonymous>)
    at parse (/Users/mike/.nvm/versions/node/v8.16.0/lib/node_modules/docsite/lib/generateJSONFile.js:27:11)
(node:67521) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:67521) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

(more description follows...)

**Comment by purple-force** [comment]
run `docsite --version`  to show the version of docsite

**Comment by GindaChen** [comment]
`v1.3.9`. Is it too low?

**Comment by purple-force** [comment]
If what it shows is not '1.3.9-wuhan2020.1'，plz install this version and tyr to run `rm -rf node_modules && npm i` and try again

**Comment by purple-force** [comment]
![image](https://user-images.githubusercontent.com/16146970/73601780-54538680-45a2-11ea-9e89-003357e0e810.png)

**Comment by purple-force** [comment]
'1.3.9-wuhan2020.1' is specific for wuhan2020web

**Comment by GindaChen** [comment]
OK it works. Thanks for your help!
