### ISSUE TITLE
docsite 安装完查看版本报错 lib下 文件

### ISSUE THREAD

**Issue by keeStep** [txd-team/docsite#67]
`> docsite@1.3.9-wuhan2020.5 postinstall D:\nvm\v8.16.0\node_modules\docsite
> opencollective-postinstall

Thank you for using docsite!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/docsite/donate

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN co-mocha@1.2.2 requires a peer of mocha@>=1.18 <6 but none is installed. You must install peer dependencies yourself.
npm WARN acorn-jsx@5.1.0 requires a peer of acorn@^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN docsite@1.3.9-wuhan2020.5 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 684 packages from 765 contributors and audited 17589 packages in 123.383s
found 7 vulnerabilities (1 moderate, 5 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

D:\nvm\v8.16.0\node_modules\docsite>docsite -V
D:\nvm\v8.16.0\node_modules\docsite\lib\generateJSONFile.js:26
  langList = [{
  ^

TypeError: Cannot destructure property `langList` of 'undefined' or 'null'.
    at Object.<anonymous> (D:\nvm\v8.16.0\node_modules\docsite\lib/generateJSONFile.js:26:5)
    at Module._compile (module.js:653:30)
    at Module._compile (D:\nvm\v8.16.0\node_modules\docsite\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (module.js:664:10)
    at Object.newLoader [as .js] (D:\nvm\v8.16.0\node_modules\docsite\node_modules\pirates\lib\index.js:104:7)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)`

**Comment by purple-force** [comment]
安装下 docsite@1.3.9-wuhan2020.6

**Comment by keeStep** [comment]
> 安装下 docsite@1.3.9-wuhan2020.6

这两个都可以吗  https://github.com/wuhan2020/wuhan2020.github.io/issues/224#issuecomment-586176176

**Comment by purple-force** [comment]
一个事情

**Comment by keeStep** [comment]
> 一个事情

D:\nvm\v8.16.0\node_modules\docsite>docsite start
(node:12556) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, scandir 'D:\nvm\v8.16.0\node_modules\docsite\src\pages'
    at Object.readdirSync (fs.js:904:18)
    at generateHTMLFile (D:\nvm\v8.16.0\node_modules\docsite\lib/generateHTMLFile.js:98:20)
    at start (D:\nvm\v8.16.0\node_modules\docsite\lib\start.js:72:3)
    at main (D:\nvm\v8.16.0\node_modules\docsite\bin\docsite.js:29:7)
    at main.next (<anonymous>)
    at onFulfilled (D:\nvm\v8.16.0\node_modules\docsite\node_modules\co\index.js:65:19)
    at D:\nvm\v8.16.0\node_modules\docsite\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at co (D:\nvm\v8.16.0\node_modules\docsite\node_modules\co\index.js:50:10)
    at Object.<anonymous> (D:\nvm\v8.16.0\node_modules\docsite\bin\docsite.js:13:1)
(node:12556) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12556) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by keeStep** [comment]
> 一个事情

说是没src，我看了下没看到src目录

**Comment by purple-force** [comment]
你这是在哪里执行的命令，start和build需要在初始化后的项目中执行的。

**Comment by keeStep** [comment]
> 你这是在哪里执行的命令，start和build需要在初始化后的项目中执行的。

DOCSITE 目录下

**Comment by keeStep** [comment]
> 你这是在哪里执行的命令，start和build需要在初始化后的项目中执行的。

![image](https://user-images.githubusercontent.com/38199712/74591772-aa6e0280-5055-11ea-856f-67f5595006bb.png)
这个步骤是不是缺少初始化

**Comment by purple-force** [comment]
这个项目是docsite init 初始化出来的，之后在这个初始化后的项目根目录下执行 start、build

**Comment by keeStep** [comment]
感谢🙏




| |
Kee
|
|
邮箱：13651486829@163.com
|

Signature is customized by Netease Mail Master

On 02/16/2020 20:38, chenliandong wrote:

这个项目是docsite init 初始化出来的，之后在这个初始化后的项目根目录下执行 start、build
