### ISSUE TITLE
参考教程报错，麻烦查一下原因，谢谢

### ISSUE THREAD

**Issue by senyer** [txd-team/docsite#69]
环境配置：
1. node-v12.16.1-x64.msi （默认配置）
2. win10专业版

报错信息如下：

``` bash
D:\Git\docsite\test>docsite start
fs.js:35
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:35:5
    at req_ (D:\Git\docsite\test\node_modules\natives\index.js:143:24)
    at Object.req [as require] (D:\Git\docsite\test\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (D:\Git\docsite\test\node_modules\vinyl-fs\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Object.require.extensions.<computed> [as .js] (D:\Git\docsite\test\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)

```

**Comment by senyer** [comment]
文档链接：
https://docsite.js.org/zh-cn/docs/installation.html

**Comment by senyer** [comment]
D:\Git\docsite\test>npm -v
6.13.4

D:\Git\docsite\test>node -v
v12.16.1

**Comment by purple-force** [comment]
目前的工程依赖还不支持node 12， 降级到node10

**Comment by senyer** [comment]
> 目前的工程依赖还不支持node 12， 降级到node10

好的，我试试看。

**Comment by senyer** [comment]
你好，我得到了另外一个错误，。

``` bash
D:\JavaDeveloper\nodejs\test1>docsite start
(node:17748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Missing binding C:\Users\Administrator\AppData\Roaming\npm\node_modules\docsite\node_modules\node-sass\vendor\win32-x64-48\binding.node
Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 6.x

Found bindings for the following environments:
  - Windows 64-bit with Node.js 6.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to download the binding for your current environment.

D:\JavaDeveloper\nodejs\test1>docsite start
(node:8932) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Missing binding C:\Users\Administrator\AppData\Roaming\npm\node_modules\docsite\node_modules\node-sass\vendor\win32-x64-48\binding.node
Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 6.x

Found bindings for the following environments:
  - Windows 64-bit with Node.js 6.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to download the binding for your current environment.

D:\JavaDeveloper\nodejs\test1>
```

**Comment by senyer** [comment]
D:\JavaDeveloper\nodejs\test1>node -v
v6.10.0

@purple-force

**Comment by purple-force** [comment]
依赖的node-sass（用于编译scss）版本，没有找到对应的绑定库 https://github.com/sass/node-sass/releases。建议用node10版本
