### ISSUE TITLE
node版本14、13、9 启动报错

### ISSUE THREAD

**Issue by YueGod** [txd-team/docsite#81]
quziwei@quziweideMacBook test % docsite start
fs.js:40
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:40:5
    at req_ (/Users/quziwei/Documents/code/web/test/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/quziwei/Documents/code/web/test/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/quziwei/Documents/code/web/test/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Object.require.extensions.<computed> [as .js] (/Users/quziwei/Documents/code/web/test/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
我试了三个版本全部报这个错

**Comment by purple-force** [comment]
试下node 10，高于10版本的还没支持。

**Comment by behappyok** [comment]
docsite 中node 12.x及以上版本和gulp3.x兼容的不是很好 ，需要这样修改
第一步  通过两个命令 npm uninstall gulp ,npm install gulp升级到gulp 到版本4 
第二步  然后修改gulpfile.js 搜索 gulp.task('default' 和  gulp.task('build',  注释掉

```
// The development server (the recommended option for development)
//gulp.task('default', ['webpack-dev-server']);

// Production build
//gulp.task('build', ['webpack:build']);
```
然后在gulpfile.js **文件末尾**增加如下代码
```
// The development server (the recommended option for development)
gulp.task('default', gulp.series( 'webpack-dev-server'));

// Production build
gulp.task('build', gulp.series( 'webpack:build'));
```

**Comment by YueGod** [comment]
好的 谢谢
