### ISSUE TITLE
Mac系统安装不成功  mac 11.6.1系统

### ISSUE THREAD

**Issue by zdl411437734** [txd-team/docsite#89]
这个是执行 安装命令 最后 添加  --python=python2
00x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 1
npm ERR! path /usr/local/lib/node_modules/docsite/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh -c node scripts/build.js
npm ERR! Building: /usr/local/bin/node /usr/local/lib/node_modules/docsite/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/usr/local/bin/node',
npm ERR! gyp verb cli   '/usr/local/lib/node_modules/docsite/node_modules/node-gyp/bin/node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.13.0 | darwin | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb cle
[2021-12-08T02_14_02_419Z-debug.log](https://github.com/txd-team/docsite/files/7672846/2021-12-08T02_14_02_419Z-debug.log)
[2021-12-08T02_18_05_983Z-debug.log](https://github.com/txd-team/docsite/files/7672847/2021-12-08T02_18_05_983Z-debug.log)
an removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` succeeded python2 /usr/local/bin/python2
npm ERR! gyp verb check python version `/usr/local/bin/python2 -c "import sys; print "2.7.15
npm ERR! gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
npm ERR! gyp verb get node dir no --target version specified, falling back to host node version: 16.13.0
npm ERR! gyp verb command install [ '16.13.0' ]
npm ERR! gyp verb install input version string "16.13.0"
npm ERR! gyp verb install installing version: 16.13.0
npm ERR! gyp verb install --ensure was passed, so won't reinstall if already installed
npm ERR! gyp verb install version is already installed, need to check "installVersion"
npm ERR! gyp verb got "installVersion" 9
npm ERR! gyp verb needs "installVersion" 9
npm ERR! gyp verb install version is good
npm ERR! gyp verb get node dir target node version installed: 16.13.0
npm ERR! gyp verb build dir attempting to create "build" dir: /usr/local/lib/node_modules/docsite/node_modules/node-sass/build
npm ERR! gyp verb build dir "build" dir needed to be created? /usr/local/lib/node_modules/docsite/node_modules/node-sass/build
npm ERR! gyp verb build/config.gypi creating config file
npm ERR! gyp verb build/config.gypi writing out config file: /usr/local/lib/node_modules/docsite/node_modules/node-sass/build/config.gypi
npm ERR! (node:72697) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp verb config.gypi checking for gypi file: /usr/local/lib/node_modules/docsite/node_modules/node-sass/config.gypi
npm ERR! gyp verb common.gypi checking for gypi file: /usr/local/lib/node_modules/docsite/node_modules/node-sass/common.gypi
npm ERR! gyp verb gyp gyp format was not specified; forcing "make"
npm ERR! gyp info spawn /usr/local/bin/python2
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/docsite/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/docsite/node_modules/node-sass/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/docsite/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/jason/.node-gyp/16.13.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/jason/.node-gyp/16.13.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/docsite/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/jason/.node-gyp/16.13.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/usr/local/lib/node_modules/docsite/node_modules/node-sass',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! ERROR:root:code for hash md5 was not found.
npm ERR! Traceback (most recent call last):
npm ERR!   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
npm ERR!     globals()[__func_name] = __get_hash(__func_name)
npm ERR!   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
npm ERR!     raise ValueError('unsupported hash type ' + name)
npm ERR! ValueError: unsupported hash type md5
npm ERR! ERROR:root:code for hash sha1 was not found.
npm ERR! Traceback (most recent call last):
npm ERR!   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
npm ERR!     globals()[__func_name] = __get_hash(__func_name)
npm ERR!   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
npm ERR!     raise ValueError('unsupported hash type ' + name)
npm ERR! ValueError: unsupported hash type sha1
npm ERR! ERROR:root:code for hash sha224 was not found.
npm ERR! Traceback (most recent call last):
npm ERR!   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
npm ERR!     globals()[__func_name] = __get_hash(__func_name)
npm ERR!   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
npm ERR!     raise ValueError('unsupported hash type ' + name)
npm ERR! ValueError: unsupported hash type sha224
npm ERR! ERROR:root:code for hash sha256 was not found.
npm ERR! Traceback (most recent call last):
npm ERR!   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
npm ERR!     globals()[__func_name] = __get_hash(__func_name)
npm ERR!   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
npm ERR!     raise ValueError('unsupported hash type ' + name)
npm ERR! ValueError: unsupported hash type sha256
npm ERR! ERROR:root:code for hash sha384 was not found.
npm ERR! Traceback (most recent call last):
npm ERR!   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
npm ERR!     globals()[__func_name] = __get_hash(__func_name)
npm ERR!   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
npm ERR!     raise ValueError('unsupported hash type ' + name)
npm ERR! ValueError: unsupported hash type sha384
npm ERR! ERROR:root:code for hash sha512 was not found.
npm ERR! Traceback (most recent call last):
npm ERR!   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
npm ERR!     globals()[__func_name] = __get_hash(__func_name)
npm ERR!   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
npm ERR!     raise ValueError('unsupported hash type ' + name)
npm ERR! ValueError: unsupported hash type sha512
npm ERR! Traceback (most recent call last):
npm ERR!   File "/usr/local/lib/node_modules/docsite/node_modules/node-gyp/gyp/gyp_main.py", line 16, in <module>
npm ERR!     sys.exit(gyp.script_main())
npm ERR!   File "/usr/local/lib/node_modules/docsite/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 545, in script_main
npm ERR!     return main(sys.argv[1:])
npm ERR!   File "/usr/local/lib/node_modules/docsite/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 538, in main
npm ERR!     return gyp_main(args)
npm ERR!   File "/usr/local/lib/node_modules/docsite/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 514, in gyp_main
npm ERR!     options.duplicate_basename_check)
npm ERR!   File "/usr/local/lib/node_modules/docsite/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 98, in Load
npm ERR!     generator.CalculateVariables(default_variables, params)
npm ERR!   File "/usr/local/lib/node_modules/docsite/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 79, in CalculateVariables
npm ERR!     import gyp.generator.xcode as xcode_generator
npm ERR!   File "/usr/local/lib/node_modules/docsite/node_modules/node-gyp/gyp/pylib/gyp/generator/xcode.py", line 7, in <module>
npm ERR!     import gyp.xcodeproj_file
npm ERR!   File "/usr/local/lib/node_modules/docsite/node_modules/node-gyp/gyp/pylib/gyp/xcodeproj_file.py", line 152, in <module>
npm ERR!     _new_sha1 = hashlib.sha1
npm ERR! AttributeError: 'module' object has no attribute 'sha1'
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/docsite/node_modules/node-gyp/lib/configure.js:345:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Darwin 20.6.0
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/docsite/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /usr/local/lib/node_modules/docsite/node_modules/node-sass
npm ERR! gyp ERR! node -v v16.13.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

这个是没有添加 --python参数的执行

npm ERR! code 1
npm ERR! path /usr/local/lib/node_modules/docsite/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh -c node scripts/build.js
npm ERR! Building: /usr/local/bin/node /usr/local/lib/node_modules/docsite/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/usr/local/bin/node',
npm ERR! gyp verb cli   '/usr/local/lib/node_modules/docsite/node_modules/node-gyp/bin/node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.13.0 | darwin | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` succeeded python2 /usr/local/bin/python2
npm ERR! gyp verb check python version `/usr/local/bin/python2 -c "import sys; print "2.7.15
npm ERR! gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
npm ERR! gyp verb get node dir no --target version specified, falling back to host node version: 16.13.0
npm ERR! gyp verb command install [ '16.13.0' ]
npm ERR! gyp verb install input version string "16.13.0"
npm ERR! gyp verb install installing version: 16.13.0
npm ERR! gyp verb install --ensure was passed, so won't reinstall if already installed
npm ERR! gyp verb install version is already installed, need to check "installVersion"
npm ERR! gyp verb got "installVersion" 9
npm ERR! gyp verb needs "installVersion" 9
npm ERR! gyp verb install version is good
npm ERR! gyp verb get node dir target node version installed: 16.13.0
npm ERR! gyp verb build dir attempting to create "build" dir: /usr/local/lib/node_modules/docsite/node_modules/node-sass/build
npm ERR! gyp verb build dir "build" dir needed to be created? /usr/local/lib/node_modules/docsite/node_modules/node-sass/build
npm ERR! gyp verb build/config.gypi creating config file
npm ERR! gyp verb build/config.gypi writing out config file: /usr/local/lib/node_modules/docsite/node_modules/node-sass/build/config.gypi
npm ERR! (node:72774) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp verb config.gypi checking for gypi file: /usr/local/lib/node_modules/docsite/node_modules/node-sass/config.gypi
npm ERR! gyp verb common.gypi checking for gypi file: /usr/local/lib/node_modules/docsite/node_modules/node-sass/common.gypi
npm ERR! gyp verb gyp gyp format was not specified; forcing "make"
npm ERR! gyp info spawn /usr/local/bin/python2
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/docsite/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/docsite/node_modules/node-sass/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/docsite/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/jason/.node-gyp/16.13.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/jason/.node-gyp/16.13.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/docsite/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/jason/.node-gyp/16.13.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/usr/local/lib/node_modules/docsite/node_modules/node-sass',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! ERROR:root:code for hash md5 was not found.
npm ERR! Traceback (most recent call last):
npm ERR!   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
npm ERR!     globals()[__func_name] = __get_hash(__func_name)
npm ERR!   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
npm ERR!     raise ValueError('unsupported hash type ' + name)
npm ERR! ValueError: unsupported hash type md5
npm ERR! ERROR:root:code for hash sha1 was not found.
npm ERR! Traceback (most recent call last):
npm ERR!   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
npm ERR!     globals()[__func_name] = __get_hash(__func_name)
npm ERR!   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
npm ERR!     raise ValueError('unsupported hash type ' + name)
npm ERR! ValueError: unsupported hash type sha1
npm ERR! ERROR:root:code for hash sha224 was not found.
npm ERR! Traceback (most recent call last):
npm ERR!   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
npm ERR!     globals()[__func_name] = __get_hash(__func_name)
npm ERR!   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
npm ERR!     raise ValueError('unsupported hash type ' + name)
npm ERR! ValueError: unsupported hash type sha224
npm ERR! ERROR:root:code for hash sha256 was not found.
npm ERR! Traceback (most recent call last):
npm ERR!   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
npm ERR!     globals()[__func_name] = __get_hash(__func_name)
npm ERR!   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
npm ERR!     raise ValueError('unsupported hash type ' + name)
npm ERR! ValueError: unsupported hash type sha256
npm ERR! ERROR:root:code for hash sha384 was not found.
npm ERR! Traceback (most recent call last):
npm ERR!   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
npm ERR!     globals()[__func_name] = __get_hash(__func_name)
npm ERR!   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
npm ERR!     raise ValueError('unsupported hash type ' + name)
npm ERR! ValueError: unsupported hash type sha384
npm ERR! ERROR:root:code for hash sha512 was not found.
npm ERR! Traceback (most recent call last):
npm ERR!   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
npm ERR!     globals()[__func_name] = __get_hash(__func_name)
npm ERR!   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
npm ERR!     raise ValueError('unsupported hash type ' + name)
npm ERR! ValueError: unsupported hash type sha512
npm ERR! Traceback (most recent call last):
npm ERR!   File "/usr/local/lib/node_modules/docsite/node_modules/node-gyp/gyp/gyp_main.py", line 16, in <module>
npm ERR!     sys.exit(gyp.script_main())
npm ERR!   File "/usr/local/lib/node_modules/docsite/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 545, in script_main
npm ERR!     return main(sys.argv[1:])
npm ERR!   File "/usr/local/lib/node_modules/docsite/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 538, in main
npm ERR!     return gyp_main(args)
npm ERR!   File "/usr/local/lib/node_modules/docsite/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 514, in gyp_main
npm ERR!     options.duplicate_basename_check)
npm ERR!   File "/usr/local/lib/node_modules/docsite/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 98, in Load
npm ERR!     generator.CalculateVariables(default_variables, params)
npm ERR!   File "/usr/local/lib/node_modules/docsite/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 79, in CalculateVariables
npm ERR!     import gyp.generator.xcode as xcode_generator
npm ERR!   File "/usr/local/lib/node_modules/docsite/node_modules/node-gyp/gyp/pylib/gyp/generator/xcode.py", line 7, in <module>
npm ERR!     import gyp.xcodeproj_file
npm ERR!   File "/usr/local/lib/node_modules/docsite/node_modules/node-gyp/gyp/pylib/gyp/xcodeproj_file.py", line 152, in <module>
npm ERR!     _new_sha1 = hashlib.sha1
npm ERR! AttributeError: 'module' object has no attribute 'sha1'
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/docsite/node_modules/node-gyp/lib/configure.js:345:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Darwin 20.6.0
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/docsite/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /usr/local/lib/node_modules/docsite/node_modules/node-sass
npm ERR! gyp ERR! node -v v16.13.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

我的node环境
(base) jason:~ jason$ node -v
v16.13.0
(base) jason:~ jason$ node-gyp -v
v8.4.1
(base) jason:~ jason$

我的python环境
(base) jason:~ jason$ python -V
Python 3.8.8
(base) jason:~ jason$ python2 -V
Python 2.7.15
(base) jason:~ jason$

**Comment by zdl411437734** [comment]
@purple-force  能帮忙看看什么原因吗？

**Comment by purple-force** [comment]
使用node 12 试试。

**Comment by zdl411437734** [comment]
好的 谢谢，我换个电脑试试 @purple-force   咱这个不支持最新的node吗？

**Comment by purple-force** [comment]
目前还不支持。
